<!--  =============== Start Main Menu ===============   -->
<div class="grid_12">
  <ul class="nav main">
    <li>
      <a href="">มาตรฐานที่ 1</a>
      <ul>
        <li>
          <a href="frmIND01.aspx">ตัวบ่งชี้ที่ 1</a>
        </li>
        <li>
          <a href="frmIND02.aspx">ตัวบ่งชี้ที่ 2</a>
        </li>
        <li>
          <a href="frmIND03.aspx">ตัวบ่งชี้ที่ 3</a>
        </li>
        <li>
          <a href="frmIND04.aspx">ตัวบ่งชี้ที่ 4</a>
        </li>
      </ul>
    </li>
    <li>
      <a href="#">มาตรฐานที่ 2</a>
      <ul>
        <li>
          <!--<a href="frmIND05.aspx">ตัวบ่งชี้ที่ 5</a>-->
          <a href="frmIND05.aspx">ตัวบ่งชี้ที่ 5</a>
        </li>
        <li>
          <a href="frmIND04_03.aspx">ตัวบ่งชี้ที่ 4.3 (สกอ)</a>
        </li>
        <li>
          <a href="frmIND06.aspx">ตัวบ่งชี้ที่ 6</a>
        </li>
        <li>
          <a href="frmIND07.aspx">ตัวบ่งชี้ที่ 7</a>
        </li>
      </ul>
    </li>
    <li>
      <a href="#">มาตรฐานที่ 3</a>
      <ul>
        <li>
          <a href="frmIND08.aspx">ตัวบ่งชี้ที่ 8</a>
        </li>
        <li>
          <a href="frmIND09.aspx">ตัวบ่งชี้ที่ 9</a>
        </li>
      </ul>
    </li>
    <li>
      <a href="#">มาตรฐานที่ 4</a>
      <ul>
        <li>
          <a href="frmIND10.aspx">ตัวบ่งชี้ที่ 10</a>
        </li>
        <li>
          <a href="frmIND11.aspx">ตัวบ่งชี้ที่ 11</a>
        </li>
      </ul>
    </li>
    <li>
      <a href="#">มาตรฐานที่ 5</a>
      <ul>
        <li>
          <a href="frmIND12.aspx">ตัวบ่งชี้ที่ 12</a>
        </li>
        <li>
          <a href="frmIND13.aspx">ตัวบ่งชี้ที่ 13</a>
        </li>
        <li>
          <a href="frmIND14.aspx">ตัวบ่งชี้ที่ 14</a>
        </li>
        <li>
          <a href="frmIND02_2.aspx">ตัวบ่งชี้ที่ 2.2 (สกอ)</a>
        </li>		 
        <li>
          <a href="frmIND02_3.aspx">ตัวบ่งชี้ที่ 2.3 (สกอ)</a>
        </li>		  
      </ul>
    </li>
    <li>
      <a href="#">มาตรฐานที่ 6</a>
      <ul>
        <li>
          <a href="frmIND15.aspx">ตัวบ่งชี้ที่ 15</a>
        </li>
      </ul>
    </li>
	<li>
      <a href="#">ตัวบ่งชี้อัตลักษณ์</a>
      <ul>
        <li>
          <a href="frmIND16.aspx">ตัวบ่งชี้ที่ 16</a>
        </li>
        <li>
          <a href="frmIND17.aspx">ตัวบ่งชี้ที่ 17</a>
        </li>
      </ul>		
    </li>
	<li>
      <a href="#">ตัวบ่งชี้มาตรการส่งเสริม</a>
      <ul>
        <li>
          <a href="frmIND18.aspx">ตัวบ่งชี้ที่ 18</a>
        </li>
      </ul>
    </li>
	  
    <li>
      <a href="frmUpload.aspx">นำเข้า Excel ไฟล์</a>
    </li>

    <li class="secondary">
      <a href="#">User Management</a>
    </li>
    <li class="secondary">
      <a href="#">Setting</a>
      <ul>
        <li>
          <a href="frmStaff.aspx">เพิ่ม/แกัไขนักวิจัย</a>
        </li>
        <li>
          <a href="frmResearch.aspx">เพิ่ม/แก้ไขงานวิจัย</a>
        </li>
      </ul>
    </li>
  </ul>
</div>
