<!--  =============== Start Main Menu ===============   -->
<div class="grid_12 slidemenu">
	<ul class="nav main">
		<li>
			<a href="frmMain.aspx">หน้าหลัก</a>
		</li>
    <li>
      <a id="linkForm00" href="frmEvaluatePart00.aspx">หน้าสรุป</a>
    </li>
    <li>
      <a id="linkFormPA" href="frmFormPA.aspx">แบบฟอร์ม PA (การพัฒนางานตามข้อตกลง)</a>
    </li>
    <!--<li>
			<a id="linkForm01" href="frmEvaluateForm.aspx">แบบฟอร์มประเมินผลงาน (2.1)</a>
		</li>-->
    <li>
      <a id="linkForm01" href="frmEvaluateFormPA.aspx">รายงานผลการปฏิบัติงาน (2.1)</a>
    </li>
    <li>
      <a id="linkForm02" href="frmEvaluatePart02.aspx">แบบฟอร์มประเมินคุณลักษณะฯ (2.2)</a>
    </li>
    <li>
      <a id="linkForm03" href="frmEvaluatePart03.aspx">แบบฟอร์มการพัฒนาและฝึกอบรม (3)</a>
    </li>
    <!--<li>
      <a href="frmEvaluateForm.aspx?result=1">ผลการประเมินฯ</a>
    </li>-->
		<!--<li>
			<a href="frmSuggestionForm.aspx">สรุประดับชั้นความสามารถ (ความคิดเห็น)</a>
		</li>-->
		<!--<li>
			<a href="frmDownload.aspx">ดาวน์โหลดแบบฟอร์ม</a>
			<ul>
				<li>
					<a href="frmDownload.aspx">แบบฟอร์ม</a>
				</li>
			</ul>
		</li>
		<li>
			<a href="frmUpload.aspx">นำเข้า Excel ไฟล์</a>
		</li>-->

		<!--<li>
			<a href="frmReport.aspx">รายงาน</a>
			<ul>
				<li>
					<a href="frmReport.aspx">รายงาน</a>
				</li>
			</ul>
		</li>-->

		<li class="secondary">
			<a href="frmLogout.aspx">ออกจากระบบ</a>
		</li>

    <!--<li class="secondary">
      <a id="linkFormPA" href="frmFormPA.aspx">แบบฟอร์ม PA (การพัฒนางานตามข้อตกลง)</a>
    </li>-->

    <li class='menuAdmin secondary'>
      <a href="#">ผู้ดูแลระบบฯ</a>
      <ul>
        <li>
          <a href="frmAddEditUser.aspx">เพิ่ม/แก้ไขผู้ใช้งาน</a>
        </li>
      </ul>
    </li>
    
	</ul>
</div>
